services:
  - type: web
    name: fastapi-blog-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "ENV_FILE=.env.prod uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENV
        value: prod
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://tresor-del.github.io
