name: Auto commit change

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'


jobs:
  auto-commit:
    runs-on: ubuntu-latest


    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false


      - name: Configure Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'


      - name: Pull latest changes
        run: |
          git pull origin main --rebase || echo 'Nothing to rebase'


      - name: Make change on run scripts
        run: |
          echo 'Update at $(date)' >> auto-update.txt

      - name: Commit if there are changes
        run: |
          git add CHANGELOG.md
          if ! git diff --cached --quiet; then
            git commit -m "Changelog auto update at $(date)"
          else
            echo "No changes to commit."
          fi

          
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}